// <auto-generated />
namespace WebGameService.Models
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dateTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dateTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201802131231140_dateTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
