// <auto-generated />
namespace WebGameService.Models
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DataTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201802121448404_DataTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
